require 'json'
require 'csv'
require 'pathname'

class SipsParser
    def initialize(nsips)
        @nsips = nsips
        
        # NSIPS(新調剤システム標準IF 共有仕様書)のフォーマットファイルを読み込む
        @nsips_format = File.open(Pathname.new(File.dirname(File.expand_path(__FILE__))).join('json').join('nsips_format.json')) do |io|
            JSON.load(io, nil, {:symbolize_names => true, :create_additions => false})
        end
    end

    def parse()
        results = []

        @nsips.split("\n").each do |record|
            rayout_type = if record.upcase.start_with?('VER')
                'header' # ヘッダ部
            else
                case record.split(/,/).first.to_i
                when 1 then 'patient' # 患者情報部
                when 2 then 'prescription' # 処方箋情報部
                when 3 then 'dosage' # 用法部
                when 4 then 'medication' # 薬品部
                when 5 then 'dispense' # 調剤録部
                when 6 then 'dispense_detail' # 調剤録明細部
                when 7 then 'additional_charge' # 加算情報部
                end 
            end
            rayout = @nsips_format[:rayouts].find{|r|r[:rayout_type] == rayout_type}
            results.concat CSV.parse(record, headers: rayout[:fields].map{|r|r[:name].to_sym}).map(&:to_hash)
        end

        @parsed_nsips = results
    end
end
__END__
[
    {
      "version": "VER010401",
      "send_datetime": "20201001235959",
      "memo": null,
      "sender_identifier": "PC01",
      "prefecture_code": "13",
      "tensuhyo": "4",
      "pharmacy_code": "1234567",
      "pharmacy_name": "メドレー薬局",
      "pharmacy_postal_code": "1066222",
      "pharmacy_address": "東京都港区六本木３ー２ー１ 住友不動産六本木グランドタワー２２Ｆ",
      "pharmacy_phone": "031234567",
      "old_filename": null
    },
    {
      "identifier": "1",
      "patient_code": "12345678",
      "kana_name": "ｶﾝｼﾞｬ ｲﾁﾛｳ",
      "kanji_name": "患者　一郎",
      "gender": "1",
      "birth_date": "19791101",
      "postal_code": "1608389",
      "address": "東京都世田谷区１?２３?４５?６７８",
      "home_phone": "0333531170",
      "work_phone": "0333531193",
      "emergency_phone": "09012345678",
      "email": "yoshinori.kodama@medley.jp",
      "copay_amount_class": "0",
      "insurance_kind": "1",
      "insurer_number": "06050116",
      "insurance_cert_date": "19990101",
      "insured_symbol": "９２０４５",
      "insured_number": "１０",
      "relationship": "1",
      "patient_payment_rate": "30",
      "insurance_payment_rate": "70",
      "business_reasons": "0",
      "senior_insurer_city_number": null,
      "senior_insured_person_number": null,
      "senior_insurance_cert_date": null,
      "public_insurer_number1": "15138092",
      "public_insured_person_number1": "9603283",
      "public_insurance_cert_date1": "19990101",
      "public_insurer_number2": null,
      "public_insured_person_number2": null,
      "public_insurance_cert_date2": null,
      "public_insurer_number3": null,
      "public_insured_person_number3": null,
      "public_insurance_cert_date3": null,
      "special_insurer_number": null,
      "special_insured_person_number": null,
      "special_insurance_cert_date": null,
      "one_packaging": "0",
      "smashing": "0",
      "caution_medicine": "0",
      "drug_interaction_check": "0",
      "drug_interaction_check_other_pharmacies": "0",
      "overdose_poisonous_drugs": "0",
      "overdose_psychotropic_drugs": "0",
      "overdose_other_drugs": "0",
      "long_term_prohibition": "0",
      "duplicate": "0",
      "duplicate_other_pharmacies": "0",
      "insurance_kind_code": "4122"
    },
    {
      "identifier": "2",
      "prescription_number": "2020100112345",
      "reception_number": "1",
      "status": "A",
      "delivery_date": "20201001",
      "expiration_date": "20201004",
      "reception_date": "20201001",
      "dispense_date": "20201001",
      "pregnancy_class": "0",
      "force_audit_indication": "0",
      "medical_institution_code_kind": "0",
      "medical_institution_code": "hoge",
      "medical_institution_receipt_code": "9999999",
      "medical_institution_prefecture_code": "13",
      "medical_institution_name": "メドレークリニック",
      "medical_institution_postalcode": "1066222",
      "medical_institution_address": "東京都港区六本木３?２?１ 住友不動産六本木グランドタワー２２Ｆ",
      "medical_institution_tel": "031234567",
      "department_code": "01",
      "department_name": "内科",
      "ward_code": null,
      "ward_name": null,
      "doctor_code": "0001",
      "doctor_kana_name": "ｲｼ ﾀﾛｳ",
      "doctor_kanji_name": "医師　太郎",
      "pharmacist_code": "9999",
      "pharmacist_name": "薬剤師　次郎",
      "doctor_consent_change_details": null,
      "doctor_doubt_answer_contents": null,
      "narcotic_use_licence_number": null,
      "narcotic_use_patient_address": null,
      "narcotic_use_patient_tel": null,
      "prescription_comment": "夜間休日等加算 (00：00)",
      "reserve": null,
      "bag_flag": "0",
      "di_flag": "0",
      "notebook_flag": "0",
      "receipt_flag": "0",
      "a_form_flag": "0",
      "b_form_flag": "0",
      "c_form_flag": "0",
      "itemized_receipt_flag": "0"
    },
    {
      "identifier": "3",
      "rp_number": "1",
      "dosage_code1": "1013044400000000",
      "dosage_name1": "内服・経口・１日３回朝昼夕食後",
      "dosage_code2": null,
      "dosage_name2": null,
      "dosage_code3": null,
      "dosage_name3": null,
      "rp_class": "2",
      "days_or_times_class": "1",
      "days_or_times": "3",
      "number_of_times": "3",
      "start_date": "20201001",
      "number_of_medications": "2",
      "rp_one_packaging": "0",
      "rp_smashing": "0",
      "dosage_comment1": null,
      "reserve": null,
      "dosage_comment2": null,
      "dosage_comment3": null,
      "dosage_comment4": null,
      "dosage_comment5": null
    },
    {
      "identifier": "4",
      "medication_number": "1",
      "rp_number": "1",
      "information_class": "1",
      "yj_code": "2233002F1174",
      "receipt_code": "610453119",
      "hot_code": "103835401",
      "medication_code": null,
      "medication_name": "ムコダイン錠２５０ｍｇ",
      "generic_name": "L-カルボシステイン",
      "imbalance_quantity1": "0",
      "imbalance_quantity2": "0",
      "imbalance_quantity3": "0",
      "imbalance_quantity4": "0",
      "imbalance_quantity5": "0",
      "imbalance_quantity6": "0",
      "dose_quantity": "3",
      "strength_flag": "1",
      "units": "錠",
      "one_packaging": "0",
      "smashing": "0",
      "image": "0",
      "separate_packaging": "0",
      "display": "1",
      "price": "8.5",
      "rack_number": null,
      "lot_number": null,
      "medication_comment1": null,
      "before_change_generic_yj_code": null,
      "before_change_generic_receipt_code": null,
      "before_change_generic_hot_code": null,
      "before_change_generic_medication_name": null,
      "mixing": "0",
      "before_change_generic_dose_quantity": null,
      "before_change_generic_units": null,
      "one_time_dose_quantity": "1",
      "medication_comment2": null,
      "medication_comment3": null,
      "medication_comment4": null,
      "medication_comment5": null,
      "generic_flag": null
    },
    {
      "identifier": "4",
      "medication_number": "2",
      "rp_number": "1",
      "information_class": "1",
      "yj_code": "6132012F1025",
      "receipt_code": "616130476",
      "hot_code": "110626901",
      "medication_code": null,
      "medication_name": "パンスポリンＴ錠１００ １００ｍｇ",
      "generic_name": "セフォチアムヘキセチル塩酸塩",
      "imbalance_quantity1": "0",
      "imbalance_quantity2": "0",
      "imbalance_quantity3": "0",
      "imbalance_quantity4": "0",
      "imbalance_quantity5": "0",
      "imbalance_quantity6": "0",
      "dose_quantity": "6",
      "strength_flag": "1",
      "units": "錠",
      "one_packaging": "0",
      "smashing": "0",
      "image": "0",
      "separate_packaging": "0",
      "display": "1",
      "price": "40.5",
      "rack_number": null,
      "lot_number": null,
      "medication_comment1": null,
      "before_change_generic_yj_code": null,
      "before_change_generic_receipt_code": null,
      "before_change_generic_hot_code": null,
      "before_change_generic_medication_name": null,
      "mixing": "0",
      "before_change_generic_dose_quantity": null,
      "before_change_generic_units": null,
      "one_time_dose_quantity": "2",
      "medication_comment2": null,
      "medication_comment3": null,
      "medication_comment4": null,
      "medication_comment5": null,
      "generic_flag": null
    },
    {
      "identifier": "3",
      "rp_number": "1",
      "dosage_code1": "1012040400000000",
      "dosage_name1": "内服・経口・１日２回朝夕食後",
      "dosage_code2": null,
      "dosage_name2": null,
      "dosage_code3": null,
      "dosage_name3": null,
      "rp_class": "2",
      "days_or_times_class": "1",
      "days_or_times": "14",
      "number_of_times": "2",
      "start_date": "20201001",
      "number_of_medications": "1",
      "rp_one_packaging": "0",
      "rp_smashing": "0",
      "dosage_comment1": null,
      "reserve": null,
      "dosage_comment2": null,
      "dosage_comment3": null,
      "dosage_comment4": null,
      "dosage_comment5": null
    },
    {
      "identifier": "4",
      "medication_number": "1",
      "rp_number": "1",
      "information_class": "1",
      "yj_code": "1132002B1060",
      "receipt_code": "610421006",
      "hot_code": "100607002",
      "medication_code": null,
      "medication_name": "アレビアチン散１０％",
      "generic_name": "フェニトイン",
      "imbalance_quantity1": "0",
      "imbalance_quantity2": "0",
      "imbalance_quantity3": "0",
      "imbalance_quantity4": "0",
      "imbalance_quantity5": "0",
      "imbalance_quantity6": "0",
      "dose_quantity": "100",
      "strength_flag": "1",
      "units": "ｇ",
      "one_packaging": "0",
      "smashing": "0",
      "image": "0",
      "separate_packaging": "0",
      "display": "1",
      "price": "12.1",
      "rack_number": null,
      "lot_number": null,
      "medication_comment1": null,
      "before_change_generic_yj_code": null,
      "before_change_generic_receipt_code": null,
      "before_change_generic_hot_code": null,
      "before_change_generic_medication_name": null,
      "mixing": "0",
      "before_change_generic_dose_quantity": null,
      "before_change_generic_units": null,
      "one_time_dose_quantity": "50",
      "medication_comment2": null,
      "medication_comment3": null,
      "medication_comment4": null,
      "medication_comment5": null,
      "generic_flag": null
    },
    {
      "identifier": "5",
      "total_amount_of_drug_costs": "568",
      "total_amount_of_dispensing_fee": "90",
      "total_amount_of_management_fee": "55",
      "medical_material_costs": "0",
      "insurance_claim_points": "611.8",
      "basic_additional_charges": "0",
      "basic_dispensing_fee": "79",
      "total_amount_of_additional_charges": "82",
      "drug_administration_management_fee": "17",
      "special_additional_charges": "28",
      "other_management_fee": "10",
      "total_points": "874",
      "copay_amount": "2620",
      "container_amount": "100",
      "other_amount": "0",
      "unpaid_amount_last_time": "200",
      "billed_amount": "2720",
      "total_billing_amount": "2920",
      "deposit_amount": "920",
      "unpaid_amount": "2000"
    },
    {
      "identifier": "6",
      "rp_number": "1",
      "dispensing_fee": "80",
      "drug_costs": "4",
      "quantity": "3",
      "subtotal": "192",
      "drug_additional_charges": "2",
      "total": "194",
      "drug_additional_charge_code1": null,
      "drug_additional_charge_contents1": null,
      "drug_additional_charge_code2": null,
      "drug_additional_charge_contents2": null,
      "drug_additional_charge_code3": null,
      "drug_additional_charge_contents3": null,
      "drug_additional_charge_code4": null,
      "drug_additional_charge_contents4": null,
      "drug_additional_charge_code5": null,
      "drug_additional_charge_contents5": null,
      "drug_additional_charge_code6": null,
      "drug_additional_charge_contents6": null,
      "drug_additional_charge_code7": null,
      "drug_additional_charge_contents7": null,
      "drug_additional_charge_code8": null,
      "drug_additional_charge_contents8": null,
      "drug_additional_charge_code9": null,
      "drug_additional_charge_contents9": null,
      "drug_additional_charge_code10": null,
      "drug_additional_charge_contents10": "A"
    },
    {
      "identifier": "6",
      "rp_number": "2",
      "dispensing_fee": "80",
      "drug_costs": "4",
      "quantity": "14",
      "subtotal": "192",
      "drug_additional_charges": "2",
      "total": "194",
      "drug_additional_charge_code1": null,
      "drug_additional_charge_contents1": null,
      "drug_additional_charge_code2": null,
      "drug_additional_charge_contents2": null,
      "drug_additional_charge_code3": null,
      "drug_additional_charge_contents3": null,
      "drug_additional_charge_code4": null,
      "drug_additional_charge_contents4": null,
      "drug_additional_charge_code5": null,
      "drug_additional_charge_contents5": null,
      "drug_additional_charge_code6": null,
      "drug_additional_charge_contents6": null,
      "drug_additional_charge_code7": null,
      "drug_additional_charge_contents7": null,
      "drug_additional_charge_code8": null,
      "drug_additional_charge_contents8": null,
      "drug_additional_charge_code9": null,
      "drug_additional_charge_contents9": null,
      "drug_additional_charge_code10": null,
      "drug_additional_charge_contents10": "A"
    },
    {
      "identifier": "7",
      "additional_charge_number": "1",
      "calculate_code": "123456789",
      "calculate_name": "加算Ａ",
      "times": "1",
      "points": "99"
    }
  ]